import type { Metadata } from "next";
import { Providers } from "@/provider/Providers";
import "./globals.css";
import {MainLayout} from "@/components/header/MainLayout";

export const metadata: Metadata = {
  title: "DVG",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Providers>
          <MainLayout>{children}</MainLayout>
        </Providers>
      </body>
    </html>
  );
}
