import type { Metadata } from "next";
import { Providers } from "@/Redux/Providers";
import HeaderFooter from "@/components/headerfooter/HeaderFooter";
import "./globals.css";
import { AnimationsProvider } from "@/components/forms/animation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased `}>
        <Providers>
          <AnimationsProvider>
            <HeaderFooter>{children}</HeaderFooter>
          </AnimationsProvider>
        </Providers>
      </body>
    </html>
  );
}
